name: Atualizar Placar UVa

on:
  schedule:
    - cron: '0 */6 * * *' # Roda a cada 6 horas
  workflow_dispatch:      # Permite rodar manualmente no botão

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Baixar repositório
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Instalar dependências
      run: |
        pip install requests

    - name: Rodar script
      run: python update_placar.py

    - name: Commit e Push das mudanças
      run: |
        git config --global user.name "Robo Placar"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Atualizacao automatica" || echo "Nada para commitar"
        git push